services:
  rabbitmq:
    extends:
      file: base.yml
      service: rabbitmq

    hostname: rabbitmq
    container_name: rabbitmq

    ports:
      - "${QUEUE_PORT:-}:5672"
      - "${QUEUE_MGMT_PORT:-}:15672"

volumes:
  rabbitmq-data:
