# Writer Extended Service
# Includes: rabbitmq (queue), mongodb (storage), writer (mongodb manager)

include:
  - path: ../../rabbitmq/docker/compose.yml
  - path: ../../mongodb/docker/compose.yml

services:
  writer:
    extends:
      file: ./compose.yml
      service: writer

    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
