packages:
  - packages/*
  - shared/*
  - services/*
  - services/_stub/*
  - dx
  - dev/tooling

injectWorkspacePackages: true

supportedArchitectures:
  libc:
    - current
    - musl

allowBuilds:
  cpu-features: true
  es5-ext: true
  esbuild: true
  nx: true
  protobufjs: true
  ssh2: true
