# Reader Module
# Includes: rabbitmq (queue), mongodb (storage), archivist (data archiver)
# Extends: feed (data fetcher, multiple instances)

include:
  - path: ../../services/rabbitmq/docker/compose.yml
  - path: ../../services/codec/docker/compose.yml

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME:-codec}-network
