# WS Extended Service
# Includes: rabbitmq, ws

include:
  - path: ../../rabbitmq/docker/compose.yml

services:
  ws:
    extends:
      file: ./compose.yml
      service: ws

    environment:
      SNAPSHOTS_URL: ${SNAPSHOTS_URL:-http://snapshots:3001}

    depends_on:
      rabbitmq:
        condition: service_healthy
      snapshots:
        condition: service_healthy
