# Depot Module
#
# Infra: db-store, registry
#
# Continuously downloads the complete BitMEX historical dataset and keeps it
# up to date as new data becomes available:
#
#   courier → S3 gzip dumps (trade, quote)                   → vault
#   scribe  → REST endpoints                                  → vault
#   tardy   → Tardis first-of-month WS history (7 WS tables) → vault

# Docker Compose Project
name: collect

include:
  - path: ../../../services/courier/docker/compose.yml
  - path: ../../../services/scribe/docker/compose.yml

  # Tardis data will not be collected unless needed, from Aug 1st 2026 onward.
  # - path: ../../../services/tardy/docker/compose.yml

networks:
  default:
    name: ${PROJECT_NAME:-tradebot}-network
    external: true
