# Rearchivist Module
# Includes: rabbitmq (queue), mongodb (storage),
#           reader (MongoDB -> RabbitMQ), codec (compress), writer (RabbitMQ -> MongoDB)

include:
  - path: ../../services/rabbitmq/docker/compose.yml
  - path: ../../services/mongodb/docker/compose.yml

services:
  rearchivist-reader:
    extends:
      file: ../../services/reader/docker/compose.yml
      service: reader
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  rearchivist-codec-1:
    extends:
      file: ../../services/codec/docker/compose.yml
      service: codec
    depends_on:
      rabbitmq:
        condition: service_healthy

  rearchivist-codec-2:
    extends:
      file: ../../services/codec/docker/compose.yml
      service: codec
    depends_on:
      rabbitmq:
        condition: service_healthy

  rearchivist-writer:
    extends:
      file: ../../services/writer/docker/compose.yml
      service: writer
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME:-tradebot}-network
    external: true
