services:
  pipe:
    build:
      context: ../../..
      dockerfile: docker/${APP_ENV:-prod}.node.Dockerfile
      args:
        SERVICE_NAME: pipe

    environment:
      QUEUE_URL: ${QUEUE_URL}

      PIPE_BINDINGS: ${PIPE_BINDINGS:-}

      LOG_LEVEL: ${LOG_LEVEL:-info}
      NODE_ENV: ${APP_ENV:-prod}

    user: "1000:1000"

    volumes:
      - ../../../:/live

    restart: on-failure
