# Trade Module
#
# Infra: bouncer
#
# The executor service receives orders from clients and posts them to BitMEX via authenticated
# websocket connections (keeps a connection pool for active clients).

# Docker Compose Project (for all trading app modules)
name: trade

include:
  - path: ../../../services/executor/docker/compose.yml

networks:
  default:
    name: ${PROJECT_NAME:-tradebot}-network
    external: true
