import type { BitmexFieldType } from '@devvir/bitmex-database';

/**
 * Metadata for an `instrument` WS `partial` message, copied from a live BitMEX
 * partial. Every partial the distiller writes carries these so a consumer can
 * seed a `bitmex-database` accumulator directly from it.
 */

/** Identity field — one row per symbol. */
export const INSTRUMENT_KEYS: string[] = ['symbol'];

/** Unfiltered partial — no symbol restriction. */
export const INSTRUMENT_FILTER: Record<string, unknown> = {};

/** Field → wire type map for every `instrument` column. */
export const INSTRUMENT_TYPES: Record<string, BitmexFieldType> = {
  symbol:                         'symbol',
  rootSymbol:                     'symbol',
  instrumentID:                   'int',
  state:                          'symbol',
  typ:                            'symbol',
  listing:                        'timestamp',
  front:                          'timestamp',
  expiry:                         'timestamp',
  settle:                         'timestamp',
  listedSettle:                   'timestamp',
  relistInterval:                 'timespan',
  positionCurrency:               'symbol',
  underlying:                     'symbol',
  quoteCurrency:                  'symbol',
  underlyingSymbol:               'symbol',
  reference:                      'symbol',
  referenceSymbol:                'symbol',
  calcInterval:                   'timespan',
  publishInterval:                'timespan',
  publishTime:                    'timespan',
  maxOrderQty:                    'long',
  minPrice:                       'float',
  maxPrice:                       'float',
  lotSize:                        'long',
  tickSize:                       'float',
  multiplier:                     'long',
  settlCurrency:                  'symbol',
  underlyingToPositionMultiplier: 'long',
  underlyingToSettleMultiplier:   'long',
  quoteToSettleMultiplier:        'long',
  isQuanto:                       'boolean',
  isInverse:                      'boolean',
  initMargin:                     'float',
  maintMargin:                    'float',
  riskLimit:                      'long',
  riskStep:                       'long',
  limit:                          'float',
  taxed:                          'boolean',
  deleverage:                     'boolean',
  makerFee:                       'float',
  takerFee:                       'float',
  settlementFee:                  'float',
  fundingBaseSymbol:              'symbol',
  fundingQuoteSymbol:             'symbol',
  fundingPremiumSymbol:           'symbol',
  fundingTimestamp:               'timestamp',
  fundingInterval:                'timespan',
  fundingRate:                    'float',
  indicativeFundingRate:          'float',
  rebalanceTimestamp:             'timestamp',
  rebalanceInterval:              'timespan',
  launchingTimestamp:             'timestamp',
  prevClosePrice:                 'float',
  limitDownPrice:                 'float',
  limitUpPrice:                   'float',
  prevTotalVolume:                'long',
  totalVolume:                    'long',
  volume:                         'long',
  volume24h:                      'long',
  prevTotalTurnover:              'long',
  totalTurnover:                  'long',
  turnover:                       'long',
  turnover24h:                    'long',
  homeNotional24h:                'float',
  foreignNotional24h:             'float',
  prevPrice24h:                   'float',
  vwap:                           'float',
  highPrice:                      'float',
  lowPrice:                       'float',
  lastPrice:                      'float',
  lastPriceProtected:             'float',
  lastTickDirection:              'symbol',
  lastChangePcnt:                 'float',
  bidPrice:                       'float',
  midPrice:                       'float',
  askPrice:                       'float',
  impactBidPrice:                 'float',
  impactMidPrice:                 'float',
  impactAskPrice:                 'float',
  hasLiquidity:                   'boolean',
  openInterest:                   'long',
  openValue:                      'long',
  fairMethod:                     'symbol',
  fairBasisRate:                  'float',
  fairBasis:                      'float',
  fairPrice:                      'float',
  markMethod:                     'symbol',
  markPrice:                      'float',
  referencePrice:                 'float',
  indicativeSettlePrice:          'float',
  settledPriceAdjustmentRate:     'float',
  settledPrice:                   'float',
  instantPnl:                     'boolean',
  minTick:                        'float',
  fundingBaseRate:                'float',
  fundingQuoteRate:               'float',
  farLegSymbol:                   'symbol',
  nearLegSymbol:                  'symbol',
  timestamp:                      'timestamp',
};
