services:
  signal:
    build:
      context: ../..
      dockerfile: docker/dev.python.Dockerfile
      args:
        SERVICE_NAME: signal
    environment:
      SERVICE_NAME: signal
      WS_URL: ${WS_URL}
      REST_URL: ${REST_URL}
      RABBITMQ_URL: ${RABBITMQ_URL}
    volumes:
      - ../../services/signal:/live/services/signal
      - ../../packages:/live/packages
    ports:
      - "3005:3000"
    restart: unless-stopped
