import { InstrumentData, BitmexSide, BitmexTickDirection } from '.';

/**
 * Action identifiers (2 bits: 0-3)
 */
export const ACTION_ID = {
  partial: 0,
  insert: 1,
  update: 2,
  delete: 3,
} as const;

export const SIDE_ID: Record<BitmexSide, 0 | 1> = {
  Buy: 0,
  Sell: 1
} as const;

export const TICK_DIRECTION: Record<BitmexTickDirection, 0 | 1 | 2 | 3> = {
  MinusTick: 0,
  ZeroMinusTick: 1,
  ZeroPlusTick: 2,
  PlusTick: 3,
} as const;

export const INSTRUMENT_KEY: Record<keyof InstrumentData, string> = {
  symbol: '',
  rootSymbol: 'R1',
  state: 'S1',
  typ: 'T1',
  listing: 'L1',
  front: 'F1',
  expiry: 'E1',
  settle: 'S2',
  listedSettle: 'L2',
  relistInterval: 'R2',
  positionCurrency: 'P1',
  underlying: 'U1',
  quoteCurrency: 'Q1',
  underlyingSymbol: 'U2',
  reference: 'R3',
  referenceSymbol: 'R4',
  calcInterval: 'C1',
  publishInterval: 'P2',
  publishTime: 'P3',
  maxOrderQty: 'M1',
  minPrice: 'M2',
  maxPrice: 'M3',
  lotSize: 'L3',
  tickSize: 'T2',
  multiplier: 'M4',
  settlCurrency: 'S3',
  underlyingToPositionMultiplier: 'U3',
  underlyingToSettleMultiplier: 'U4',
  quoteToSettleMultiplier: 'Q2',
  isQuanto: 'I1',
  isInverse: 'I2',
  initMargin: 'I3',
  maintMargin: 'M5',
  riskLimit: 'R5',
  riskStep: 'R6',
  limit: 'L4',
  taxed: 'T3',
  deleverage: 'D1',
  makerFee: 'M6',
  takerFee: 'T4',
  settlementFee: 'S4',
  fundingBaseSymbol: 'F2',
  fundingQuoteSymbol: 'F3',
  fundingPremiumSymbol: 'F4',
  fundingTimestamp: 'F5',
  fundingInterval: 'F6',
  fundingRate: 'F7',
  indicativeFundingRate: 'I4',
  rebalanceTimestamp: 'R7',
  rebalanceInterval: 'R8',
  launchingTimestamp: 'L5',
  prevClosePrice: 'P4',
  limitDownPrice: 'L6',
  limitUpPrice: 'L7',
  prevTotalVolume: 'P5',
  totalVolume: 'T5',
  volume: 'V1',
  volume24h: 'V2',
  prevTotalTurnover: 'P6',
  totalTurnover: 'T6',
  turnover: 'T7',
  turnover24h: 'T8',
  homeNotional24h: 'H1',
  foreignNotional24h: 'F8',
  prevPrice24h: 'P7',
  vwap: 'V3',
  highPrice: 'H2',
  lowPrice: 'L8',
  lastPrice: 'L9',
  lastPriceProtected: 'L10',
  lastTickDirection: 'L11',
  lastChangePcnt: 'L12',
  bidPrice: 'B1',
  midPrice: 'M7',
  askPrice: 'A1',
  impactBidPrice: 'I5',
  impactMidPrice: 'I6',
  impactAskPrice: 'I7',
  hasLiquidity: 'H3',
  openInterest: 'O1',
  openValue: 'O2',
  fairMethod: 'F9',
  fairBasisRate: 'F10',
  fairBasis: 'F11',
  fairPrice: 'F12',
  markMethod: 'M8',
  markPrice: 'M9',
  indicativeSettlePrice: 'I8',
  settledPriceAdjustmentRate: 'S5',
  settledPrice: 'S6',
  instantPnl: 'I9',
  minTick: 'M10',
  fundingBaseRate: 'F13',
  fundingQuoteRate: 'F14',
  farLegSymbol: 'F15',
  nearLegSymbol: 'N1',
  timestamp: 'T9',
} as const;
